import{i as l,S as d}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const u="44778442-2a526b123707daef27dd3bad3";function f(t){const s=`https://pixabay.com/api/?key=${u}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(s).then(r=>{if(!r.ok)throw new Error("Network response was not ok");return r.json()}).then(r=>r.hits).catch(r=>(console.error("Error fetching data:",r),[]))}function m(){const t=document.querySelector("#gallery");t.innerHTML=""}function i(t){l.error({title:"Error",message:t,position:"topCenter"})}function p(){l.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"})}function y(){const t=document.getElementById("loaderContainer");t&&(t.style.display="block")}function c(){const t=document.getElementById("loaderContainer");t&&(t.style.display="none")}const h=document.querySelector("#search-form"),g=document.querySelector("#search-input"),L=document.querySelector("#gallery"),w=new d(".gallery a");h.addEventListener("submit",async function(t){t.preventDefault();const s=g.value.trim();if(s===""){i("Please enter a search term");return}m(),y();try{const r=await f(s);if(c(),r.length===0){p();return}r.forEach(n=>{const e=document.createElement("div");e.classList.add("gallery-item"),e.innerHTML=`
        <a href="${n.largeImageURL}" data-lightbox="image">
          <img src="${n.webformatURL}" alt="${n.tags}">
          <div class="details">
            <p>Likes: ${n.likes}</p>
            <p>Views: ${n.views}</p>
            <p>Comments: ${n.comments}</p>
            <p>Downloads: ${n.downloads}</p>
          </div>
        </a>
      `,L.appendChild(e)}),w.refresh()}catch(r){c(),console.error("Error searching images:",r),i("Failed to fetch images. Please try again later.")}});
//# sourceMappingURL=commonHelpers.js.map
