import{i as c}from"./assets/vendor-ad859c2f.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const l="44778442-2a526b123707daef27dd3bad3";async function u(s){const n=`https://pixabay.com/api/?key=${l}&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const r=await fetch(n);if(!r.ok)throw new Error("Network response was not ok");return(await r.json()).hits}catch(r){return console.error("Error fetching data:",r),[]}}function d(){const s=document.querySelector("#gallery");s.innerHTML=""}function i(s){c.error({title:"Error",message:s,position:"topCenter"})}function f(){c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"})}const p=document.querySelector("#search-form"),m=document.querySelector("#search-input"),y=document.querySelector("#gallery");p.addEventListener("submit",async function(s){s.preventDefault();const n=m.value.trim();if(n===""){i("Please enter a search term");return}d();try{const r=await u(n);if(r.length===0){f();return}r.forEach(t=>{const e=document.createElement("div");e.classList.add("gallery-item"),e.innerHTML=`
                <img src="${t.webformatURL}" alt="${t.tags}" data-large="${t.largeImageURL}">
                <div class="details">
                    <p>Likes: ${t.likes}</p>
                    <p>Views: ${t.views}</p>
                    <p>Comments: ${t.comments}</p>
                    <p>Downloads: ${t.downloads}</p>
                </div>
            `,y.appendChild(e)})}catch(r){console.error("Error searching images:",r),i("Failed to fetch images. Please try again later.")}});
//# sourceMappingURL=commonHelpers.js.map
